fix the server.js dying in centos issue

diff --git a/templates/default/nodejs.initd.erb b/templates/default/nodejs.initd.erb
--- a/templates/default/nodejs.initd.erb
+++ b/templates/default/nodejs.initd.erb
@@ -10,7 +10,7 @@
 USER="<%= @user %>"
 GROUP="<%= @group %>"
 
-DAEMON="<%= @binary_path %>"
+BINARY="<%= @binary_path %>"
 
 ROOT_DIR="<%= @app_dir %>"
 
@@ -24,7 +24,7 @@ do_start()
         export HOME=$ROOT_DIR
         if [ ! -f "$LOCK_FILE" ] ; then
                 echo -n $"Starting $SERVER: "
-                runuser -l "$USER" -c "$DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure
+                daemon --user "$USER" "$BINARY $SERVER >> $LOG_FILE &" && echo_success || echo_failure
                 RETVAL=$?
                 echo
                 [ $RETVAL -eq 0 ] && touch $LOCK_FILE
@@ -37,7 +37,7 @@ do_stop()
 {
         echo -n $"Stopping $SERVER: "
         pid=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}'`
-        kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
+        pkill -TERM -P $pid > /dev/null 2>&1 && echo_success || echo_failure
         RETVAL=$?
         echo
         [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
@@ -53,9 +53,6 @@ case "$1" in
         restart)
                 do_stop
                 do_start
-                ;;
-        status)
-                status $DAEMON
                 ;;
         *)
                 echo "Usage: $0 {start|stop|restart}"
